version: "3.7"

services:
  api01: &api
    hostname: api01
    # image: erickmarx/rinha-2024-q1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8081
    restart: "on-failure"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    stdin_open: false
    pull_policy: always
    volumes:
      - sqlite_data:/home/bun/app/data
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "250MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - PORT=8082
    depends_on:
      - api01

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - api01
      - api02
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

volumes:
  sqlite_data:
